#!/usr/bin/env php
<?php

/**
 * © 2018 - Phoponent
 * Author: Nicolas Choquet
 * Email: nicolachoquet06250@gmail.com
 * LICENSE GPL ( GNU General Public License )
 */

namespace phoponent;
require "phoponent/Autoload.php";
	loading\Auto::load();
	try {
        framework\static_classe\command::go($argv);
	}
	catch (\Exception $e) {
		exit($e->getMessage()."\n");
	}